title: Hello world
author: Sam
theme: minima
email: admin@mail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello world of Sam 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
---
title: "Hello world"
date: 2020-11-05
---
